### ISSUE TITLE
Pipeline Skript in Module aufteilen

### ISSUE THREAD

**Issue by soenkekueper** [set-de/jenkins_ws#10]

**Comment by foto-andreas** [comment]
Ggf. können hiermit auch Modul-Test der Pipeline Module realisiert werden. Man könnte die Module der Stages oder Steps nicht nur getrennt in Test-Workflows aufrufen, sondern auch Stubs dafür schreiben.

**Comment by foto-andreas** [comment]
- Pipeline ist grundlegend aufgeräumt 

Offen: 
- Aufteilen in getrennte Dateien 
- noch Überflüssiges?
- Methoden thematisch sortieren

**Comment by warntjenbset** [comment]
IM-527
