### ISSUE TITLE
Pipeline mit Branches testen / beschreiben

### ISSUE THREAD

**Issue by soenkekueper** [set-de/jenkins_ws#13]

**Comment by tobiasbaum** [comment]
Zwei Pipelines machen, eine für das automatische Bauen aus dem Trunk, eine für Bauen aus Branches. Hintergrund: Wenn zwischen den Trunk-Builds irgendwelche Branch-Builds kommen, dann machen die u.a. die Checkstyle-Ratcheting-Histore kaputt. Auch sonst könnten die sich ins Gehege kommen. Intern gehen beide Builds natürlich auf das gleiche Pipeline-Skript.

**Comment by warntjenbset** [comment]
IM-526
