### ISSUE TITLE
Jenkins-Konfiguration in SCM speichern

### ISSUE THREAD

**Issue by foto-andreas** [set-de/jenkins_ws#27]
https://wiki.jenkins-ci.org/display/JENKINS/SCM+Sync+configuration+plugin

**Comment by TwoStone** [comment]
Sollten wir dafür das POSYng Repository nehmen oder ein eigenes?

**Comment by foto-andreas** [comment]
- O. g. Plugin ist nicht geeignet. 
- sollte wenn, dann nicht in POSYng-Repo gespeichert werden, oder zumindest nicht in Workspace oder Programme
- ggf. Backup-Plugin nutzen
- oder nur Matzes Backup?

**Comment by warntjenbset** [comment]
Man könnte folgendes Plugin benutzen: https://wiki.jenkins-ci.org/display/JENKINS/thinBackup

- Es kann Zeitgesteuert über den Jenkins gestartet werden (Cron Notation)
- Differentielle Backups
- Zahl der Genrationen kann definiert werden, andere nette Aufräum-Features...
- Kann die Plugins mit wegsichern

**Comment by foto-andreas** [comment]
Backup, Staging, etc.

**Comment by warntjenbset** [comment]
IM-523
