### ISSUE TITLE
statische Analyse-Ergebnisse aufsammeln checkstyle/findbugs/codenarc/classycle

### ISSUE THREAD

**Issue by soenkekueper** [set-de/jenkins_ws#3]

**Comment by tobiasbaum** [comment]
Das bisher genutzte Violations-Plugin ist nicht Pipeline-fähig. Die Einzelplugins für Checkstyle und FindBugs sehen besser aus (und sind auch schon in der aktuellen Pipeline drin). Das Ratcheting läuft bei denen allerdings etwas anders.

Aktuell scheint die Konfiguration noch nicht ganz zu passen, das passe ich jetzt gleich mal an.
