### ISSUE TITLE
Bessere Verteilung der Builds auf Knoten

### ISSUE THREAD

**Issue by foto-andreas** [set-de/jenkins_ws#37]
- Wenn zwei Pipelines laufen, müssen die unbedingt auf die Knoten verteilt werden. Prüfen ob das so ist.
- Für die Übergangszeit sollten parallel laufende Linux-intensive Jobs auf Knoten verteilt werden. Es ist blöd, wenn CheckCommit und Pipeline gleichzeitig laufen, womöglich noch SystemTestLinux, alles auf dem gleichen Knoten.

**Comment by warntjenbset** [comment]
IM-519
