### ISSUE TITLE
Benachrichtigung der Culprits je Step

### ISSUE THREAD

**Issue by soenkekueper** [set-de/jenkins_ws#8]
Hipchat und E-Mail

Wenn Culprits (Leute die den Build instabil gemacht haben) schwierig ist dann globable Benachrichtigung

**Comment by foto-andreas** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Static+Code+Analysis+Plug-ins#StaticCodeAnalysisPlug-ins-remoteapi

**Comment by foto-andreas** [comment]
https://plugins.jenkins.io/emailext-template

**Comment by foto-andreas** [comment]
Ist jetzt implementiert. Es muss dann noch in Verbindung mit SVN geprüft werden, ob die richtigen Leute angeschrieben werden.
